Add the missing TimeManagement.class
Exception in thread "main" java.lang.NoClassDefFoundError: edu/rice/rubbos/beans/TimeManagement
	at edu.rice.rubbos.client.ClientEmulator.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: edu.rice.rubbos.beans.TimeManagement
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)